public enum TipoToken {
    PALAVRA_CHAVE,
    IDENTIFICADOR,
    SIMB,
    DECL_VARIAVEL,
    TIPO_INT,
    TIPO_REAL,
    NUM_INT,
    NUM_REAL,
    BOOLEAN,
    SIMB_ATRIBUICAO,
    SIMB_ABRE_PAR,
    SIMB_FECHA_PAR,
    CMD_CONDICAO,
    CMD_REPETICAO,
    OPERADOR,
    OPERADOR_MULT,
    OPERADOR_DIV,
    OPERADOR_LOGICO,
    OPERADOR_NEGADO,
    ERRO;

}
